# Generated by Django 5.1.7 on 2025-03-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('product_id', models.CharField(max_length=250, null=True)),
                ('order_id', models.CharField(max_length=250, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
